import React, { useState } from 'react'
import { Button, Modal } from 'react-bootstrap';
import { useSelector } from 'react-redux';

const ModalDialog = ({
    show,
    otp,
    handleClose,
    onChangeOTP,
    verifyNow
}) => {
    const { qrCode, secretCode } = useSelector(state => state?.twofactor)
    console.log("modal response==>", qrCode, secretCode);
    return (
        <>
            <Modal show={show} onHide={handleClose} animation={false}>
                <Modal.Header closeButton>
                    <Modal.Title>Scan an Authenticator App</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <p>An  authenticator app will have the sign in the codes ready when multi factor authetication is required for your Redis Labs account.</p>
                    <br />
                    <input type="secret" value={secretCode} class="field left" id="secret" readOnly />
                    <p>Enter this code into your two-factor authentication app or scan the QR code below.</p>
                    <br />
                    <h6>1. Scan this QR code with the authenticator app</h6>
                    <br />
                    <img src={qrCode} alt="qrCode" class="rounded mx-auto d-block" />
                    <br />
                    <h6>2. Enter the code generated by your authenticator app</h6>
                    <input
                        type="otp"
                        placeholder='Enter the OTP'
                        value={otp}
                        onChange={(e) => onChangeOTP(e)}
                        class="field left"
                        id="otp"
                        maxLength={6} />

                </Modal.Body>
                <Modal.Footer>
                    {/* <Button variant="secondary" onClick={handleClose}>
                        Close
                    </Button> */}
                    <Button variant="primary" onClick={() => verifyNow(otp)}>
                        Verify
                    </Button>
                </Modal.Footer>
            </Modal>
        </>
    );
}

export default ModalDialog
